"""
Test data factories for generating test objects.
"""

# Import all factory classes for easy access
from .user_factory import (
    UserFactory,
    AdminUserFactory,
    ManagerUserFactory,
    DeveloperUserFactory,
    InactiveUserFactory,
    APIKeyFactory,
    ExpiredAPIKeyFactory,
    HighUsageAPIKeyFactory,
    create_user_with_api_keys,
    create_test_user_set,
    create_user_with_specific_permissions
)

from .release_factory import (
    ReleaseFactory,
    ProcessingReleaseFactory,
    ReadyReleaseFactory,
    DeliveredReleaseFactory,
    LiveReleaseFactory,
    FailedReleaseFactory,
    SingleReleaseFactory,
    AlbumReleaseFactory,
    EPReleaseFactory,
    TrackFactory,
    HighQualityTrackFactory,
    ExplicitTrackFactory,
    ReleaseAssetFactory,
    ArtworkAssetFactory,
    AudioAssetFactory,
    VideoAssetFactory,
    DocumentAssetFactory,
    create_single_release_with_track,
    create_album_with_tracks,
    create_release_with_assets,
    create_complete_release,
    create_release_test_set
)

from .partner_factory import (
    DeliveryPartnerFactory,
    DSPPartnerFactory,
    AggregatorPartnerFactory,
    DistributorPartnerFactory,
    PlatformPartnerFactory,
    InactivePartnerFactory,
    PendingPartnerFactory,
    SuspendedPartnerFactory,
    APIKeyAuthPartnerFactory,
    OAuth2PartnerFactory,
    BasicAuthPartnerFactory,
    BearerTokenPartnerFactory,
    PartnerConfigFactory,
    APIKeyConfigFactory,
    ClientCredentialsConfigFactory,
    WebhookSecretConfigFactory,
    TimeoutConfigFactory,
    BatchSizeConfigFactory,
    create_partner_with_configs,
    create_complete_partner_set,
    create_partner_with_full_config,
    create_high_priority_partners,
    create_partners_by_territory
)

__all__ = [
    # User factories
    'UserFactory',
    'AdminUserFactory',
    'ManagerUserFactory',
    'DeveloperUserFactory',
    'InactiveUserFactory',
    'APIKeyFactory',
    'ExpiredAPIKeyFactory',
    'HighUsageAPIKeyFactory',
    'create_user_with_api_keys',
    'create_test_user_set',
    'create_user_with_specific_permissions',
    
    # Release factories
    'ReleaseFactory',
    'ProcessingReleaseFactory',
    'ReadyReleaseFactory',
    'DeliveredReleaseFactory',
    'LiveReleaseFactory',
    'FailedReleaseFactory',
    'SingleReleaseFactory',
    'AlbumReleaseFactory',
    'EPReleaseFactory',
    'TrackFactory',
    'HighQualityTrackFactory',
    'ExplicitTrackFactory',
    'ReleaseAssetFactory',
    'ArtworkAssetFactory',
    'AudioAssetFactory',
    'VideoAssetFactory',
    'DocumentAssetFactory',
    'create_single_release_with_track',
    'create_album_with_tracks',
    'create_release_with_assets',
    'create_complete_release',
    'create_release_test_set',
    
    # Partner factories
    'DeliveryPartnerFactory',
    'DSPPartnerFactory',
    'AggregatorPartnerFactory',
    'DistributorPartnerFactory',
    'PlatformPartnerFactory',
    'InactivePartnerFactory',
    'PendingPartnerFactory',
    'SuspendedPartnerFactory',
    'APIKeyAuthPartnerFactory',
    'OAuth2PartnerFactory',
    'BasicAuthPartnerFactory',
    'BearerTokenPartnerFactory',
    'PartnerConfigFactory',
    'APIKeyConfigFactory',
    'ClientCredentialsConfigFactory',
    'WebhookSecretConfigFactory',
    'TimeoutConfigFactory',
    'BatchSizeConfigFactory',
    'create_partner_with_configs',
    'create_complete_partner_set',
    'create_partner_with_full_config',
    'create_high_priority_partners',
    'create_partners_by_territory'
]